import { esc } from '../utils/helpers.js';
import { renderDeckListComponent, renderProgressBar } from '../components/uiComponents.js';

export function renderDecksPage(ctx){
  const { myDecks, starterDecks, archivedDecks, deckProgress, masteredPct, activeCards, dueCards, showArchive, points } = ctx;
  const deckCard = d => `<div class="panel"><div class="space"><div><div class="row wrap"><div class="h3">${esc(d.name)}</div>${d.starter?'<span class="badge">Starter</span>':''}</div><div class="small">${activeCards(d).length} cards · ${dueCards(d).length} due today</div></div><button class="btn inline" onclick="openDeck('${d.id}')">Open</button></div><div style="height:10px"></div>${renderProgressBar(deckProgress(d))}<div class="space" style="margin-top:8px"><div class="tiny">${deckProgress(d)}% known</div><div class="tiny">${masteredPct(d)}% mastered</div></div></div>`;
  const archivedCard = d => `<div class="panel"><div class="space"><div><div class="h3">${esc(d.name)}</div><div class="small">${activeCards(d).length} cards</div></div><div class="row"><button class="btn secondary inline" onclick="restoreDeck('${d.id}')">Restore</button><button class="btn danger inline" onclick="deleteDeckPermanently('${d.id}')">Delete</button></div></div></div>`;

  return `<div class="card"><div class="h1">Decks</div><div class="small" style="margin-top:6px">Create, import, edit, and organize your study material.</div><div class="tiny" style="margin-top:8px">${points} points</div><div style="height:12px"></div><div class="grid3"><button class="btn" onclick="showCreateDeck()">Create Deck</button><button class="btn secondary" onclick="showImportDeck()">Import File</button><button class="btn secondary" onclick="showPasteText()">Paste Text</button></div><div style="height:8px"></div><button class="btn secondary" onclick="toggleArchiveView()">${showArchive ? 'Hide Archive' : `View Archive (${archivedDecks.length})`}</button></div><div class="card"><div class="h2">My Decks</div><div style="height:10px"></div>${renderDeckListComponent(myDecks, deckCard)}</div><div class="card"><div class="h2">Starter Decks</div><div style="height:10px"></div>${renderDeckListComponent(starterDecks, deckCard)}</div>${showArchive?`<div class="card"><div class="h2">Archived Decks</div><div class="small" style="margin-top:6px">Restore a deck or delete it permanently.</div><div style="height:10px"></div>${renderDeckListComponent(archivedDecks, archivedCard)}</div>`:''}`;
}
