import { esc } from '../utils/helpers.js';
import { renderFlashcardComponent, renderQuizComponent, renderMatchingComponent } from '../components/uiComponents.js';

export const renderStudyHubPage = decks => `<div class="card"><div class="h1">Study</div><div class="small" style="margin-top:6px">Pick a deck and start quickly.</div></div>${decks.length?`<div class="list">${decks.map(d=>`<div class="panel"><div class="space"><div><div class="h3">${esc(d.name)}</div><div class="small">${d.cardCount} cards · ${d.due} due today</div></div><button class="btn secondary inline" onclick="openDeck('${d.id}')">View</button></div><div style="height:12px"></div><div class="grid3"><button class="btn" onclick="startStudy('${d.id}','flashcard')">Flashcards</button><button class="btn secondary" onclick="startStudy('${d.id}','quiz')">Quiz</button><button class="btn ghost" onclick="startStudy('${d.id}','matching')">Matching Game</button></div></div>`).join('')}</div>`:'<div class="card empty">No decks with cards yet.</div>'}`;

export function renderStudyCardPage({ deckName, index, total, mode, text, flipped, options, showAudio=false, quizState=null }){
  return `<div class="card"><div class="space"><div><div class="h1">${esc(deckName)}</div><div class="small">${mode} · ${index}/${total}</div></div><button class="btn secondary inline" onclick="navigate('study')">Exit</button></div><div style="height:12px"></div>${mode==='quiz'?`<div class="flashcard" style="min-height:180px">${esc(text)}</div>${showAudio?`<div style="height:10px"></div><button class="btn secondary" onclick="speakStudyCard('front')">🔊 Play Front</button>`:''}<div style="height:12px"></div>${renderQuizComponent(options, quizState || undefined)}${quizState?.answered?`<div style="height:10px"></div><button class="btn" onclick="nextQuizQuestion()">Next Question</button>`:''}`:`<div onclick="flipStudyCard()">${renderFlashcardComponent({text,flipped})}</div>${showAudio?`<div style="height:10px"></div><div class="grid2"><button class="btn secondary" onclick="speakStudyCard('front')">🔊 Play Front</button><button class="btn secondary" onclick="speakStudyCard('back')">🔊 Play Back</button></div>`:''}<div style="height:12px"></div>${flipped?`<div class="grid3"><button class="btn warning" onclick="rateCard('hard')">Hard</button><button class="btn secondary" onclick="rateCard('medium')">Medium</button><button class="btn success" onclick="rateCard('easy')">Easy</button></div>`:'<button class="btn" onclick="flipStudyCard()">Show Answer</button>'}`}</div>`;
}

export function renderMatchingGamePage({ deckName, index, total, matching }){
  return `<div class="card"><div class="space"><div><div class="h1">${esc(deckName)}</div><div class="small">Matching game · ${index}/${total} matched</div></div><button class="btn secondary inline" onclick="navigate('study')">Exit</button></div><div style="height:12px"></div>${renderMatchingComponent(matching)}</div>`;
}
