import { esc } from '../utils/helpers.js';
import { renderFlashcardComponent, renderQuizComponent, renderMatchingComponent } from '../components/uiComponents.js';

export const renderStudyHubPage = decks => `<div class="card"><div class="h1">Study</div><div class="small" style="margin-top:6px">Pick a deck and start quickly.</div></div>${decks.length?`<div class="list">${decks.map(d=>`<div class="panel"><div class="space"><div><div class="h3">${esc(d.name)}</div><div class="small">${d.cardCount} cards · ${d.due} due today</div></div><button class="btn secondary inline" onclick="openDeck('${d.id}')">View</button></div><div style="height:12px"></div><div class="row wrap"><button class="btn inline" onclick="startStudy('${d.id}','flashcard')">Flashcards</button><button class="btn secondary inline" onclick="startStudy('${d.id}','quiz')">Quiz</button><button class="btn ghost inline" onclick="startStudy('${d.id}','typed')">Type Answer</button><button class="btn ghost inline" onclick="startStudy('${d.id}','matching')">Matching Game</button></div></div>`).join('')}</div>`:'<div class="card empty">No decks with cards yet.</div>'}`;

export function renderStudyCardPage({ deckName, index, total, mode, text, flipped, options, showAudio=false, quizState=null, typedState=null }){
  const modeLabel = mode === 'typed' ? 'Type answer mode' : mode;
  return `<div class="card"><div class="space"><div><div class="h1">${esc(deckName)}</div><div class="small">${modeLabel} · ${index}/${total}</div></div><button class="btn secondary inline" onclick="navigate('study')">Exit</button></div><div style="height:12px"></div>${mode==='quiz'?`<div class="flashcard" style="min-height:180px">${esc(text)}</div>${showAudio?`<div style="height:10px"></div><button class="btn secondary" onclick="speakStudyCard('front')">🔊 Play Front</button>`:''}<div style="height:12px"></div>${renderQuizComponent(options, quizState || undefined)}${quizState?.answered?`<div style="height:8px"></div><div class="small ${quizState.correct ? 'success' : ''}">${quizState.correct ? 'Correct!' : 'Incorrect – keep practicing'}</div><div style="height:10px"></div><button class="btn" onclick="nextQuizQuestion()">Next Question</button>`:''}`:mode==='typed'?`<div class="panel typed-active-recall"><div class="small">Prompt</div><div class="h2" style="margin-top:6px">${esc(text)}</div></div>${showAudio?`<div style="height:10px"></div><button class="btn secondary" onclick="speakStudyCard('front')">🔊 Play Front</button>`:''}<div style="height:12px"></div><input id="typed-answer-input" class="${typedState?.submitted ? (typedState.correct ? 'typed-input-correct' : 'typed-input-wrong') : ''}" ${typedState?.submitted?'disabled':''} value="${esc(typedState?.userAnswer || "").replace(/"/g,'&quot;')}" placeholder="Type your answer">${typedState?.submitted?`<div style="height:8px"></div><div class="small typed-result ${typedState.correct ? 'correct' : 'wrong'}">${typedState.correct ? 'Correct' : `Incorrect. Correct answer: ${esc(typedState.correctAnswer || '')}`}</div><div style="height:10px"></div><button class="btn" onclick="nextTypedQuestion()">Next Question</button>`:`<div style="height:10px"></div><button class="btn" onclick="submitTypedAnswer()">Submit Answer</button>`}`:`<div onclick="flipStudyCard()">${renderFlashcardComponent({text,flipped})}</div>${showAudio && !flipped?`<div style="height:10px"></div><button class="btn secondary" onclick="speakStudyCard('front')">🔊 Play Front</button>`:''}${showAudio && flipped?`<div style="height:10px"></div><button class="btn secondary" onclick="speakStudyCard('back')">🔊 Play Answer</button>`:''}<div style="height:12px"></div>${flipped?`<div class="grid3"><button class="btn warning" onclick="rateCard('hard')">Hard</button><button class="btn secondary" onclick="rateCard('medium')">Medium</button><button class="btn success" onclick="rateCard('easy')">Easy</button></div>`:'<button class="btn" onclick="flipStudyCard()">Show Answer</button>'}`}</div>`;
}

export function renderMatchingGamePage({ deckName, index, total, matching }){
  return `<div class="card"><div class="space"><div><div class="h1">${esc(deckName)}</div><div class="small">Matching game · ${index}/${total} matched</div></div><button class="btn secondary inline" onclick="navigate('study')">Exit</button></div><div style="height:12px"></div>${renderMatchingComponent(matching)}</div>`;
}
